[CommandUnavailable]
hash = "sha1-bfed234d466faaa491252c3b967ea72e8febeb62"
other = "コマンドを使用できません"

[LanguageHandlerSame]
hash = "sha1-d4201bc6bf738be94f7f9f60025695136ac8623c"
other = "Your language is already {{.Lang}}."

[LanguageHandlerSet]
hash = "sha1-aab5ce35b6cea5532c4299bf8a461ba9c48aac2e"
other = "Your language set to {{.Lang}}."
