ASAP = "asap"
AskForLocation = "Or send me your location!"
Cancel = "Cancel"
ChangePickupTime = "Change pickup time"
CommandUnavailable = "Command unavailable"
Confirmation = "Language"
DriverAcceptedJob = "Driver accepts the job. Please meet at designated location {{.LocalTime}}"
Duration = "Duration"
English = "🇺🇸 English"
EstTravelTime = "Estimated travel time"
HHMM = "at {{.hhmm}}."
Help = "Help"
HowDoYouLikeService = "How do you like our service this time?"
Japanese = "🇯🇵 Japanese"
LanguageIsTheSame = "Your language is already {{.Lang}}."
LanguagePickerTitle = "Language selector"
LanguageSetTo = "Your language set to {{.Lang}}."
ListOfAvailableCommands = "List of available commands"
LocationOptions = "Location options"
NothingChanged = "Error, nothing changed"
PickFromListBelow = "Pick from the list below"
Pickup = "Pickup"
ReservationCancelled = "Your reservation cancelled."
ReservationConfirmation = "Your reservation: confirmation"
ReservationIncompleted = "The reservation isn't completed yet."
RideConfirmation = "Ride confirmation"
RideInitLine = "Need a ride now?"
RideIsDone = "The ride is done."
RideReservationCompleted = "Your ride reservation is done."
Thai = "🇹🇭 Thai"
ThankYouSeeYouAgain = "Thank you for your feedback. We hope to see you again."
Time = "Time"
To = "To"
TravelMeter = "{{.Meter}} m\n{{.FreeFlowMinute}} min w/o traffic"
TravelMinute = "{{.Min}} min"
WalkInstead = "I'll walk instead"
WelcomeAboard = "Welcome aboard!"
WhichOne = "Which one do you prefer?"
Yes = "Yes"
